# Esercizio 1

Definire i  numpy array a=[1.2, 5.4, 6, 1.59] e b=[5.2, 1.2, 1.5, 2] ed eseguire le seguenti operazioni:
  - calcolare la radice quadrata degli elementi di a;
   - calcolare 𝑒xp(𝑎/2) ;
   - calcolare il vettore somma tra a e b ;
   - moltiplicare ogni elemento di a per il corrispondente elemento di b;
   - creare un vettore di valori uniformemente equispaziati tra 0 e 30 con passo  0.5;
   - creare un vettore di 100 valori uniformemente equispaziati tra 1 e 2.
   - usare linspace() per creare un numpy array 2x6 con prima riga di 6 valori uniformi compresi tra 10 e 20 e seconda riga 6 valori     
      uniformi compresi tra  20 e 10;
   - calcolare il prodotto scalare tra a e b;
   - creare la matrice A che ha come righe i vettori a e b ;
   - calcolare il prodotto scalare tra i due vettori a e b;
   - eseguire il prodotto della matrice A per il vettore b e assegnarlo ad y;
   - costruire una matrice diagonale D a partire dal vettore a;

In [2]:
import math
import numpy as np
a = np.array([1.2, 5.4, 6, 1.59])
b = np.array([5.2, 1.2, 1.5, 2])

print('radice quad:', np.sqrt(a))
print('exp(a/2):', np.exp(a / 2))
print('sum:', a+b)
print('moltiplication:', a*b)
print('30 passo 0.5:\n', np.arange(0, 30, 0.5, dtype = float))
print('1 e 2 100 numeri:\n',np.linspace(1, 2, 1)) #99
print('10-20 e 20-10:\n', np.array([np.linspace(10, 20, 6), np.linspace(20, 10, 6)]))
print('prodotto scalare:', np.sum(a * b))
A=np.array([a, b])
print('matrice righe a e b:\n', A)
print('prodotto scalare tra vettori:', np.dot(a,b))
print('prodotto della matrice A per il vettore b:\n', np.dot(A, b))
print('matrice diagonale a partire da a:\n', np.diag(a))

radice quad: [1.09544512 2.32379001 2.44948974 1.26095202]
exp(a/2): [ 1.8221188  14.87973172 20.08553692  2.214441  ]
sum: [6.4  6.6  7.5  3.59]
moltiplication: [6.24 6.48 9.   3.18]
30 passo 0.5:
 [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5]
1 e 2 100 numeri:
 [1.]
10-20 e 20-10:
 [[10. 12. 14. 16. 18. 20.]
 [20. 18. 16. 14. 12. 10.]]
prodotto scalare: 24.9
matrice righe a e b:
 [[1.2  5.4  6.   1.59]
 [5.2  1.2  1.5  2.  ]]
prodotto scalare tra vettori: 24.9
prodotto della matrice A per il vettore b:
 [24.9  34.73]
matrice diagonale a partire da a:
 [[1.2  0.   0.   0.  ]
 [0.   5.4  0.   0.  ]
 [0.   0.   6.   0.  ]
 [0.   0.   0.   1.59]]


# Esercizio 2

Costruire  i seguenti Numpy array 2d utilizzando il minor numero di istruzioni possibili

<img src="ese2.png" width="500">

In [3]:
#Matrice A
print(np.concatenate((np.full((3,3),2), np.full((3,1), 3)), axis=1),'\n')
#Matrice B
print(np.concatenate((np.diag((2, 2, 2)), np.tile(np.arange(1, 11), (3,1))), axis=1), '\n')
#Matrice C
print(np.diag([2]*5) + np.diag(([-1]*4), k=1) + np.diag(([-1]*4), k=-1), '\n')
#Matrice D
print(np.concatenate((np.concatenate((np.concatenate((np.full((2,2),2), np.full((2,2),3)), axis=1), np.zeros((2,4))), axis=0), np.concatenate((np.zeros((2,2)), np.diag((5,5))), axis=1)), axis=0))

[[2 2 2 3]
 [2 2 2 3]
 [2 2 2 3]] 

[[ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]] 

[[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]] 

[[2. 2. 3. 3.]
 [2. 2. 3. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


# Esercizio 3

Calcolare la somma dei primi n numeri naturali dispari sia utilizzando un ciclo for che servendosi dell'istruzione sum di numpy.

scegli i primi n:  0


0


# Esercizo 4

Scrivere una function Python per generare l'n-esimo termine (n > 2) della successione
di Fibonacci. Scrivere poi una function ricorsiva che risolva lo stesso problema
e confrontare i tempi di calcolo delle due functions per n = 24.

Ricordiamo la formula per generare i i numeri di Fibonacci:

$$F_0=1$$
$$F_1=1$$
$$F_n = F_{n-1} + F_{n-2}, \quad n=2,...$$

In [45]:
def fiboIter():
    n=int(input('numero:'))
    a, b = 0, 1
    for i in range(n-1):
        temp = a
        a = b
        b = temp + b
    return a

print(fiboIter())

def fiboRec(n):
    if n <= 0:
        return "n > 0"
    elif n == 1:
        return 0
    elif n == 2:
        return 1
    else:
        return fiboRec(n-1) + fiboRec(n-2)
'''non so fare'''
n=int(input('numero:'))
print(fiboRec(num))

numero: 24


28657


numero: 24


5
