## Esercizi sui Numpy array  5 Marzo 2024


**Esercizio 1**

Confrontare il tempo di esecuzione dei due metodi per la creazione di un numpy array di 2000000 di elementi equidistanti nell'intervallo [-4,4]:

    1) costruzione con utilizzo di np.linspace
    
    2) Assegnazione manuale dei valori nel ciclo.
    

In [1]:
import numpy as np
import time
start = time.time()
b = np.linspace(-4, 4, 2000000)
end = time.time()
t1 = start - end
start = time.time()
a = []
for i in range(-1000000, 1000001):
    a.insert(i+1000000, i/1000000 * 4)
end = time.time()
t2 = start-end
print('secondi per linspace: ', t1, '\nsecondi per inserimento manuale: ', t2)

secondi per linspace:  -0.0055081844329833984 
secondi per inserimento manuale:  -0.4037322998046875


**Esercizio 2**

-     Creare un numpy array 1D (chiamato c) di valori equidistanti tra 7 e 41 con step 2.

-      Trasformare l'array c in un numpy array 2d (chiamato c1) con shape (2,9) usando il metodo .reshape((m,n))

-       Determinare se c1 e' una copia o una vista dell'originale.

In [2]:
c=np.arange(7,43,2)
c1 = c.reshape((2,9))
c1 = [10, 10]
print(c, '\n', c1)

#il metodo reshape restituisce una copia --> non modifica l'originale

[ 7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41] 
 [10, 10]


**Esercizio 3**

-     Costruire un numpy array 1d, denominato $C$ di valori che variano tra 15 e 41 con step 2

-     Trasformarlo in un numpy array 2d con shape(7,2) usando il metodo . resize(7,2)  che lavora in-place,  (cioè  modifica l'array esistente, non è necessario creare una copia). Verificare la shape di C e dire se C è copia o vista?

In [3]:
C = np.arange(15,43,2)
print(C, '\t', C.shape)
C.resize(7,2)
print(C, '\t', C.shape)
#C è una vista --> modifica anche l'originale

[15 17 19 21 23 25 27 29 31 33 35 37 39 41] 	 (14,)
[[15 17]
 [19 21]
 [23 25]
 [27 29]
 [31 33]
 [35 37]
 [39 41]] 	 (7, 2)


**Esercizio 4**

-      Costruire il numpy array  s  formato da 100 valori equidistanti in  [0,4],

-      considerarne il reshape in un array 2d che ha 4 righe con un numero opportuno di colonne

In [4]:
s = np.linspace(0,4,100)
print(s)
s.resize(4, 25)
print(s)

[0.         0.04040404 0.08080808 0.12121212 0.16161616 0.2020202
 0.24242424 0.28282828 0.32323232 0.36363636 0.4040404  0.44444444
 0.48484848 0.52525253 0.56565657 0.60606061 0.64646465 0.68686869
 0.72727273 0.76767677 0.80808081 0.84848485 0.88888889 0.92929293
 0.96969697 1.01010101 1.05050505 1.09090909 1.13131313 1.17171717
 1.21212121 1.25252525 1.29292929 1.33333333 1.37373737 1.41414141
 1.45454545 1.49494949 1.53535354 1.57575758 1.61616162 1.65656566
 1.6969697  1.73737374 1.77777778 1.81818182 1.85858586 1.8989899
 1.93939394 1.97979798 2.02020202 2.06060606 2.1010101  2.14141414
 2.18181818 2.22222222 2.26262626 2.3030303  2.34343434 2.38383838
 2.42424242 2.46464646 2.50505051 2.54545455 2.58585859 2.62626263
 2.66666667 2.70707071 2.74747475 2.78787879 2.82828283 2.86868687
 2.90909091 2.94949495 2.98989899 3.03030303 3.07070707 3.11111111
 3.15151515 3.19191919 3.23232323 3.27272727 3.31313131 3.35353535
 3.39393939 3.43434343 3.47474747 3.51515152 3.55555556 3.595959

**Esercizio 5**

-     Costruire il numpy array s formato da 100 valori equidistanti in  [0,4]
-     considerarne il reshape in un array 2d che ha 4 colonne con un numero opportuno di righe

In [5]:
s1 = np.linspace(0,4,100)
print(s1)
s1.resize(25, 4)
print(s1)

[0.         0.04040404 0.08080808 0.12121212 0.16161616 0.2020202
 0.24242424 0.28282828 0.32323232 0.36363636 0.4040404  0.44444444
 0.48484848 0.52525253 0.56565657 0.60606061 0.64646465 0.68686869
 0.72727273 0.76767677 0.80808081 0.84848485 0.88888889 0.92929293
 0.96969697 1.01010101 1.05050505 1.09090909 1.13131313 1.17171717
 1.21212121 1.25252525 1.29292929 1.33333333 1.37373737 1.41414141
 1.45454545 1.49494949 1.53535354 1.57575758 1.61616162 1.65656566
 1.6969697  1.73737374 1.77777778 1.81818182 1.85858586 1.8989899
 1.93939394 1.97979798 2.02020202 2.06060606 2.1010101  2.14141414
 2.18181818 2.22222222 2.26262626 2.3030303  2.34343434 2.38383838
 2.42424242 2.46464646 2.50505051 2.54545455 2.58585859 2.62626263
 2.66666667 2.70707071 2.74747475 2.78787879 2.82828283 2.86868687
 2.90909091 2.94949495 2.98989899 3.03030303 3.07070707 3.11111111
 3.15151515 3.19191919 3.23232323 3.27272727 3.31313131 3.35353535
 3.39393939 3.43434343 3.47474747 3.51515152 3.55555556 3.595959

**Esercizio 6**  

-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo .ravel()  
-     Si tratta di una copia o di una vista?

In [6]:
A = np.array([[10,11,12],[13,14,15],[16,17,18]])
print(A, '\n')
print(A.ravel(), '\n')
print(A, '\n')
#è una copia

[[10 11 12]
 [13 14 15]
 [16 17 18]] 

[10 11 12 13 14 15 16 17 18] 

[[10 11 12]
 [13 14 15]
 [16 17 18]] 



**Esercizio 7**  

-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo  .flatten().
-     Si tratta di una copia o di una vista?

In [7]:
A1 = np.array([[10,11,12],[13,14,15],[16,17,18]])
print(A1, '\n')
print(A1.flatten(), '\n')
print(A1, '\n')
#è una copia -> non modifica i dati

[[10 11 12]
 [13 14 15]
 [16 17 18]] 

[10 11 12 13 14 15 16 17 18] 

[[10 11 12]
 [13 14 15]
 [16 17 18]] 



**Esercizio 8** 

-     creare i due  numpy array 1d
        f1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]  
        f2= [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
-     "vederli" come matrici  4x4 ed effettuarne il prodotto scalare, memorizzando in f3 la matrice che nasce dal loro prodotto.

In [8]:
f1 = np.linspace(0, 15 ,16)  
f2 = np.linspace(16, 31, 16)
print(f1, f2)
f1.resize(4,4)
f2.resize(4,4)
print('\n',f1, f2)
f3 = np.dot(f1, f2)
print('\n',f3)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.] [16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31.]

 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]] [[16. 17. 18. 19.]
 [20. 21. 22. 23.]
 [24. 25. 26. 27.]
 [28. 29. 30. 31.]]

 [[ 152.  158.  164.  170.]
 [ 504.  526.  548.  570.]
 [ 856.  894.  932.  970.]
 [1208. 1262. 1316. 1370.]]


**Esercizio 9**    

 Costruire:
-      Numpy Array A di shape (2,10) : array di valori random campionati da una distribuzione gaussiana con media 0 e varianza 1.
 -     Numpy array 1D B di shape (20,) formato dagli interi da 0 a 19.
 
 "Vedere" A come un array 1D di 20 elementi ed effettuare la somma di A+B



In [9]:
A = np.arange(1, 21, 1)
A.resize(2,10)
B = np.linspace(0,19,20)
print(A, '\n', B, '\n', A.flatten()+B)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]] 
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.] 
 [ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39.]


**Esercizio 10** 
-     Creare un array 2D di shape (5,5), denominato B2, con valori tutti uguali a 15.
-     Creare una copia B3 di B2. Modificare l'elemento B3[0,0] assegnandogli il valore 150. 
-     Stampare il numpy array B2 ed il numpy array B3 e verificare che B2, dopo la modifica di B3, è rimasto inalterato

In [10]:
B2 = np.full((5,5), 15)
B3 = B2.copy()
B3[0,0] = 150
print(B2, '\n\n', B3)

[[15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]] 

 [[150  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]]


**Esercizio 11**   

-     Costruire  un numpy array 1D, di shape (10,) denominato  f , costituito da 10 valori equidistanti nell'intervallo [0,1]
-     aumentarne la dimensionalità, in maniera tale che abbia shape (10,1)

In [11]:
f = np.linspace(0,1,10)
f.resize(10,1)
print(f)

[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [0.44444444]
 [0.55555556]
 [0.66666667]
 [0.77777778]
 [0.88888889]
 [1.        ]]


- **Esercizio 12**
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per righe


In [24]:
a= np.array([14,13,12,11])
b=np.array([[4,3,2,1],[9,10,11,12]])
print(np.concatenate((a.reshape((1,4)),b), axis=0))

[[14 13 12 11]
 [ 4  3  2  1]
 [ 9 10 11 12]]


- **Esercizio 13**
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])

-
- Costruire il numpy array che si ottiene concatenando a e b per colonne

In [32]:
a= np.array([14,13,12,11])
b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])
print(np.column_stack((a,b)))

[[14  4  3  2  1]
 [13  9 10 11 12]
 [12  4  3  2  1]
 [11  9 10 11 12]]


**Esercizio 14**

Costruire, facendo uso di una sola riga di codice, la matrice A di ordine 10, che ha gli unici elementi diversi da zero, sulla diagonale princiaple, sulla codiagonale inferiore e sulla codiagonale superiore:

elementi diagonali $A_{i,i}=10 \quad$, i=1,20

elementi nella codiagonale inferiore $A_{i-1,i}=-12, \quad$ i=2,..,20, 

elementi nella codiagonale superiore $A_{i,i+1}=-2 \quad$ i=1,..,19

In [14]:
A = np.diag([10]*10) + np.diag([-12]*9, k=-1) + np.diag([-2]*9, k=1)
print(A)

[[ 10  -2   0   0   0   0   0   0   0   0]
 [-12  10  -2   0   0   0   0   0   0   0]
 [  0 -12  10  -2   0   0   0   0   0   0]
 [  0   0 -12  10  -2   0   0   0   0   0]
 [  0   0   0 -12  10  -2   0   0   0   0]
 [  0   0   0   0 -12  10  -2   0   0   0]
 [  0   0   0   0   0 -12  10  -2   0   0]
 [  0   0   0   0   0   0 -12  10  -2   0]
 [  0   0   0   0   0   0   0 -12  10  -2]
 [  0   0   0   0   0   0   0   0 -12  10]]


**Esercizio 15**

Costruire la matrice identità, denominata *I*,  della stessa dimensione di *A*

In [15]:
I = np.full_like(A, 323)
print(I)

[[323 323 323 323 323 323 323 323 323 323]
 [323 323 323 323 323 323 323 323 323 323]
 [323 323 323 323 323 323 323 323 323 323]
 [323 323 323 323 323 323 323 323 323 323]
 [323 323 323 323 323 323 323 323 323 323]
 [323 323 323 323 323 323 323 323 323 323]
 [323 323 323 323 323 323 323 323 323 323]
 [323 323 323 323 323 323 323 323 323 323]
 [323 323 323 323 323 323 323 323 323 323]
 [323 323 323 323 323 323 323 323 323 323]]


**Esercizio 16**

Facendo uso dell'operatore slicing *:* ,costruire la matrice AA selezionando dalla matrice A le righe che vanno dalla 2 alla 9 con step 2 e le colonne che vanno dalla 3 alla 6 con step 2.
La matrice AA è una vista o una copia?


In [91]:
AA = A[2:9:2, 3:6:2]
print(AA)
AA[1,1] = 50030
print(A)
#è una vista -> modifica i valori

[[   -2     0]
 [  -12 50030]
 [    0   -12]
 [    0     0]]
[[   10    -2     0     0     0     0     0     0     0     0]
 [  -12    10    -2     0     0     0     0     0     0     0]
 [    0   -12    10    -2     0     0     0     0     0     0]
 [    0     0   -12    10    -2     0     0     0     0     0]
 [    0     0     0   -12    10 50030     0     0     0     0]
 [    0     0     0     0   -12    10    -2     0     0     0]
 [    0     0     0     0     0   -12    10    -2     0     0]
 [    0     0     0     0     0     0   -12    10    -2     0]
 [    0     0     0     0     0     0     0   -12    10    -2]
 [    0     0     0     0     0     0     0     0   -12    10]]


**Esercizio 17**

Facendo uso dell'operatore slicing *:*, costruire la matrice A1 selezionando dalla matrice A le colonne che vanno dalla 1 alla 5 con step 2.  Trasforma la matrice A1 in una copia.

In [39]:
A1 = A[:, 1:6:2]
A1 = A1.copy()
print(A1, '\n\n', A)

[[ -2   0   0]
 [ 10   0   0]
 [-12  -2   0]
 [  0  10   0]
 [  0 -12  -2]
 [  0   0  10]
 [  0   0 -12]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]] 

 [[ 10  -2   0   0   0   0   0   0   0   0]
 [-12  10  -2   0   0   0   0   0   0   0]
 [  0 -12  10  -2   0   0   0   0   0   0]
 [  0   0 -12  10  -2   0   0   0   0   0]
 [  0   0   0 -12  10  -2   0   0   0   0]
 [  0   0   0   0 -12  10  -2   0   0   0]
 [  0   0   0   0   0 -12  10  -2   0   0]
 [  0   0   0   0   0   0 -12  10  -2   0]
 [  0   0   0   0   0   0   0 -12  10  -2]
 [  0   0   0   0   0   0   0   0 -12  10]]


**Esercizio 18**

Costruisci due numpy array A e B di shape (5,5) 
   - A formata da numeri interi casuali  nell'intervallo [1,20]
   - B formata da numeri interi casuali  nell'intervallo [1,6]
 
  Costruisci con una sola riga di codice le seguenti matrici
  
  C=A+B   dove  $\quad c_{ij}=a_{ij}+b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  D=A-B   dove  $\quad d_{ij}=a_{ij}-b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  E=A*B   dove  $\quad e_{ij}=a_{ij}*b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  F=A\B   dove  $\quad f_{ij}=a_{ij}\b_{ij} \quad i=0,..,n, \quad j=0,...,n$

In [111]:
A = np.random.randint(1, 20, size=(5,5))
B = np.random.randint(1, 6, size=(5,5))
print(A, '\n\n', B)
C, D, E, F = A+B, A-B, A*B, A/B
print('\n', C, '\n\n', D, '\n\n', E, '\n\n', F)

[[18  5 17 14 18]
 [12  4 15 15 18]
 [ 5 19 17 13  2]
 [13 19  1  6 12]
 [17 16  2  3  7]] 

 [[1 2 1 3 2]
 [4 4 3 4 5]
 [2 3 1 5 5]
 [5 2 1 3 4]
 [1 3 4 4 3]]

 [[19  7 18 17 20]
 [16  8 18 19 23]
 [ 7 22 18 18  7]
 [18 21  2  9 16]
 [18 19  6  7 10]] 

 [[17  3 16 11 16]
 [ 8  0 12 11 13]
 [ 3 16 16  8 -3]
 [ 8 17  0  3  8]
 [16 13 -2 -1  4]] 

 [[18 10 17 42 36]
 [48 16 45 60 90]
 [10 57 17 65 10]
 [65 38  1 18 48]
 [17 48  8 12 21]] 

 [[18.          2.5        17.          4.66666667  9.        ]
 [ 3.          1.          5.          3.75        3.6       ]
 [ 2.5         6.33333333 17.          2.6         0.4       ]
 [ 2.6         9.5         1.          2.          3.        ]
 [17.          5.33333333  0.5         0.75        2.33333333]]


**Esercizio 19**

Costruisci la matrice ottenuta facendo il prodotto scalare tra le  matrici A e B (righe per colonne)

In [112]:
np.dot(A,B)

array([[160, 189, 136, 273, 256],
       [151, 169, 126, 244, 233],
       [182, 169, 100, 223, 248],
       [133, 153, 125, 186, 186],
       [107, 131,  98, 162, 157]])

**Esercizio 20**

Costruisci l'array ottenuto sommando gli elementi delle righe della matrice B usando l'appropriata funzione di Numpy.

In [113]:
print(B.sum(axis=1))

[ 9 20 16 15 15]


**Esercizio 21** 

Costruisci l'array ottenuto sommando gli elementi delle colonne della matrice B usando l'appropriata funzione di Numpy.

In [114]:
print(B.sum(axis=0))

[13 14 10 19 19]


**Esercizio 22** 

Somma tutti gli elementi di B usando l'appropriata funzione di Numpy.

In [115]:
print(B.sum())

75


**Esercizio 23**

Calcolare il minimo degli elementi di B, tra le righe, tra le colonne, il minimo di tutta la matrice B

In [116]:
print('min tra colonne:', B.min(axis=0), 'min tra righe:', B.min(axis=1), 'min totale:', B.min())

min tra colonne: [1 2 1 3 2] min tra righe: [1 3 1 1 1] min totale: 1


**Esercizio 24**

Calcola e memorizza in un vettore la somma degli elementi di ogni colonna di $ |B |$. Calcola successivamente il massimo di questo vettore.
$maxsc= \max_{j=1,n} \sum_{i} |b_{ij}|$

In [117]:
print(np.max(B.sum(axis=0)))

19


**Esercizio 25**
Calcola, memorizzando in un vettore, la somma degli elementi di ogni riga  di $ |B |$. Calcola successivamente il massimo di questo vettore.
$maxsr= \max_{i=1,n} \sum_{j} |b_{ij}|$

In [118]:
print(np.max(B.sum(axis=1)))

20


**Esercizio 26**

Effettua nella matrice B lo scambio tra la  riga 2 e  la riga 3

In [119]:
row2, row3 = B[1, :].copy(), B[2, :].copy()
print(row2, '\n', row3, '\n\n', B)
B[1], B[2] = row3, row2
print('\n\n', B)

[4 4 3 4 5] 
 [2 3 1 5 5] 

 [[1 2 1 3 2]
 [4 4 3 4 5]
 [2 3 1 5 5]
 [5 2 1 3 4]
 [1 3 4 4 3]]


 [[1 2 1 3 2]
 [2 3 1 5 5]
 [4 4 3 4 5]
 [5 2 1 3 4]
 [1 3 4 4 3]]


**Esercizio 27**

Calcola il valore massimo della colonna 0-esima della matrice B e l'indice di riga a cui appartiene

In [125]:
print(B,'\n\nil max della prima colonna è:', np.max(B[:, 0]), '\n\nil max della prima colonna si trova nella riga', np.where(B[:, 0] == np.max(B[:, 0]))[0][0])

[[1 2 1 3 2]
 [2 3 1 5 5]
 [4 4 3 4 5]
 [5 2 1 3 4]
 [1 3 4 4 3]] 

il max della prima colonna è: 5 

il max della prima colonna si trova nella riga 3


**Esercizio 28**   


Scrivi una funzione border(m,n,visualizza=False) che:
-      crea un array 2D di shape(m,n) che abbia tutti valori nulli
-     imposta ad 1  i valori degli elementi sul bordo dell'array (prima ed ultima riga, prima e l'ultima colonna)
-      Preveda un argomento di default che se impostato a True visualizza la matrice

In [151]:
def border(m, n, visualizza=False):
    mat = np.zeros((m,n))
    mat[0, :], mat[:, 0], mat[m-1, :], mat[:, n-1] = 1,1,1,1
    if visualizza:
        print(mat)
        
border(10, 10, True)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Esercizio 29**

Scrivi una funzione `visualizza(f,a,b)`che prende in input una lambda function f, gli estremi dell'intervallo [a,b] su cui è definita e la visualizzi in una finestra grafica

Chaima la funzione passandogli la funzione f(x)=sin(2*$\pi$*x), [a,b]=[0,2*$\pi$]

In [163]:
import matplotlib.pyplot as plt
import math

def visualizza(f,a,b):
    return math.cos(math.pi)

f = lambda x: math.sin(2*x*math.pi) 
visualizza(f, 0, 2*math.pi)

-1.0

**Esercizio 30**

Scrivi una funzione `visualizza2(f,a,b,f2,a2,b2)`che prende in input una lambda function f e gli estremi dell'intervallo [a,b]  su cui è definita, una lambda function f2 e gli estremi dell'intervallo su cui è definita [a2,b2] e le visualizzi sulla stessa finestra grafica.

Chaima la funzione passandogli  una funzione f(x) quadratica ed una funzione f2(x) exponenziale ed [a,b]=[0,2]

In [ ]:
def visualizza2(f,a,b,f2,a2,b2):
    
    
f1
f2
visualizza2(f1, 0, 2, f2, 0, 2)